port: 80
log:
  level: debug
database:
  type: postgres
  host: database
  port: 5432
  username: tgs
  password: ''
  database: tgs
notifier-bot:
  token: TOKEN
https:
  port: 443
  key: /ssl/troublor_xyz.key
  cert: /ssl/troublor_xyz.crt
