port: 80
log:
  level: debug
database:
  type: postgres
  host: database
  port: 5432
  username: tgs
  password: ''
  database: tgs
#notifier-bot:
#  token: 1898800830:AAGc5Z478ewCTQEaHLDh8HFThte59b7vDDE
https:
  port: 443
  key: /ssl/tgs.key
  cert: /ssl/tgs.crt
